#!/usr/bin/env ruby

require 'pathname'

$:.unshift "#{ENV['MUNIN_LIBDIR']}/plugins" if ENV['MUNIN_LIBDIR']
$:.unshift Pathname.new(__FILE__).realpath.dirname.to_s

require "plugin"
require "resque"

def output_values
  puts "workers.value #{stats['resque']['workers']}"
  puts "working.value #{stats['resque']['working']}"
end

def output_config
  puts <<-END
graph_category BackgroundJobs
graph_title Resque workers pending
graph_vlabel Workers
graph_order workers working
workers.label total workers
workers.type GAUGE
workers.draw AREA
workers.colour ccff00
working.label active workers
working.type GAUGE
working.draw AREA
working.colour 0033ff
END
  exit 0
end

if ARGV[0] == "config"
  output_config
else
  output_values
end
