#!/usr/bin/env ruby

require 'pathname'

$:.unshift "#{ENV['MUNIN_LIBDIR']}/plugins" if ENV['MUNIN_LIBDIR']
$:.unshift Pathname.new(__FILE__).realpath.dirname.to_s

require "plugin"
require "resque"

def output_values
  stats['queues'].each { |name, value|
    puts "queue_#{clean_fieldname(name)}.value #{value}";
  }
end

def output_config
  puts "graph_category BackgroundJobs"
  puts "graph_title Resque queues"
  puts "graph_vlabel Queues"
  stats['queues'].each { |name, value|
    puts "queue_#{clean_fieldname(name)}.label #{name}";
    puts "queue_#{clean_fieldname(name)}.type GAUGE";
    puts "queue_#{clean_fieldname(name)}.draw LINE1";
    puts "queue_#{clean_fieldname(name)}.warning #{stats['resque']['workers'] * 2}";
    puts "queue_#{clean_fieldname(name)}.critical #{stats['resque']['workers'] * 5}";
  }
  exit 0
end

if ARGV[0] == "config"
  output_config
else
  output_values
end
